// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssepbgrxoxaqffpofgpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzZXBiZ3J4b3hhcWZmcG9mZ3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTc5NTcsImV4cCI6MjA3MzU5Mzk1N30.UvDjjH1sApdVon4O5dbyi4sisMbR4mKYeudvXk2WGsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});